"""add_registration_date_to_participant

Revision ID: 10f0bfc2f41a
Revises: 54a966aa7d2d
Create Date: 2026-06-07 19:33:05.177752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f0bfc2f41a'
down_revision = '54a966aa7d2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('registrationDate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'registrationDate')
    # ### end Alembic commands ###