"""initial_schema

Revision ID: 238a911f9ba3
Revises: None
Create Date: 2026-05-20 16:46:16.494207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238a911f9ba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashedPassword', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hackathons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prizePool', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('isOnline', sa.Boolean(), nullable=True),
    sa.Column('isPrivate', sa.Boolean(), nullable=True),
    sa.Column('votingType', sa.String(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.Column('registrationDeadline', sa.DateTime(), nullable=False),
    sa.Column('maxParticipants', sa.Integer(), nullable=True),
    sa.Column('currentParticipants', sa.Integer(), nullable=True),
    sa.Column('organizerId', sa.Integer(), nullable=False),
    sa.Column('minTeamSize', sa.Integer(), nullable=True),
    sa.Column('maxTeamSize', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizerId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathons_id'), 'hackathons', ['id'], unique=False)
    op.create_table('hackathon_allow_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathonId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hackathonId'], ['hackathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_allow_list_id'), 'hackathon_allow_list', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inviteCode', sa.String(), nullable=False),
    sa.Column('hackathonId', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hackathonId'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inviteCode')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathonId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('contextRole', sa.String(), nullable=False),
    sa.Column('registrationDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hackathonId'], ['hackathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_hackathon_allow_list_id'), table_name='hackathon_allow_list')
    op.drop_table('hackathon_allow_list')
    op.drop_index(op.f('ix_hackathons_id'), table_name='hackathons')
    op.drop_table('hackathons')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###