"""add_timezone_to_verification_token

Revision ID: 54a966aa7d2d
Revises: b9cc3d5235d5
Create Date: 2026-06-05 21:56:58.310448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54a966aa7d2d'
down_revision = 'b9cc3d5235d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('registration_start', sa.DateTime(), nullable=False))
    op.add_column('hackathons', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('hackathons', 'registrationStart')
    op.drop_column('hackathons', 'imageUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hackathons', sa.Column('registrationStart', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('hackathons', 'image_url')
    op.drop_column('hackathons', 'registration_start')
    # ### end Alembic commands ###