"""fix_enums_to_strings

Revision ID: 83ce5f9fd426
Revises: 78a332bb6ff7
Create Date: 2026-05-17 21:21:21.132057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83ce5f9fd426'
down_revision = '78a332bb6ff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hackathons', 'votingType',
               existing_type=postgresql.ENUM('JUDGES', 'PARTICIPANTS', 'ALL_USERS', name='votingtype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('participants', 'contextRole',
               existing_type=postgresql.ENUM('PARTICIPANT', 'JUDGE', name='contextrole'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'contextRole',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PARTICIPANT', 'JUDGE', name='contextrole'),
               existing_nullable=False)
    op.alter_column('hackathons', 'votingType',
               existing_type=sa.String(),
               type_=postgresql.ENUM('JUDGES', 'PARTICIPANTS', 'ALL_USERS', name='votingtype'),
               existing_nullable=False)
    # ### end Alembic commands ###