"""add_teams_and_team_sizes

Revision ID: 8efd5d7da51c
Revises: efbb44ab2b33
Create Date: 2026-05-17 17:56:38.557630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8efd5d7da51c'
down_revision = 'efbb44ab2b33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inviteCode', sa.String(), nullable=False),
    sa.Column('hackathonId', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hackathonId'], ['hackathons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_inviteCode'), 'teams', ['inviteCode'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathonId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hackathonId'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.add_column('hackathons', sa.Column('prizePool', sa.String(), nullable=True))
    op.add_column('hackathons', sa.Column('isOnline', sa.Boolean(), nullable=True))
    op.add_column('hackathons', sa.Column('registrationDeadline', sa.DateTime(), nullable=False))
    op.add_column('hackathons', sa.Column('minTeamSize', sa.Integer(), nullable=False))
    op.add_column('hackathons', sa.Column('maxTeamSize', sa.Integer(), nullable=False))
    op.alter_column('hackathons', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('hackathons', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('hackathons', 'maxParticipants',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('hackathons_organizerId_fkey'), 'hackathons', type_='foreignkey')
    op.create_foreign_key(None, 'hackathons', 'users', ['organizerId'], ['id'])
    op.drop_column('hackathons', 'createdAt')
    op.drop_column('hackathons', 'status')
    op.drop_column('hackathons', 'imageUrl')
    op.drop_column('hackathons', 'registrationStart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('registrationStart', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('hackathons', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hackathons', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hackathons', sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hackathons', type_='foreignkey')
    op.create_foreign_key(op.f('hackathons_organizerId_fkey'), 'hackathons', 'users', ['organizerId'], ['id'], ondelete='CASCADE')
    op.alter_column('hackathons', 'maxParticipants',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hackathons', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('hackathons', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('hackathons', 'maxTeamSize')
    op.drop_column('hackathons', 'minTeamSize')
    op.drop_column('hackathons', 'registrationDeadline')
    op.drop_column('hackathons', 'isOnline')
    op.drop_column('hackathons', 'prizePool')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_teams_inviteCode'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###